version: "3.5"

services:
  db:
    image: postgres:10-alpine
    ports:
      - "5421:5432"
    container_name: tt-database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./dumps/init.sql:/docker-entrypoint-initdb.d/init.sql
  server:
    depends_on:
      - db
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: tt-server
    ports:
      - "8080:8080"
    environment:
      DB_URL: postgres://postgres@db:5432
    volumes:
      - .:/usr/src/app/

volumes:
  pgdata:
  dumps:
